CapstoneMVC/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapstoneMVC.Models;
using CapstoneMVC.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace CapstoneMVC.Controllers
{
    public class QuestionsController : Controller
    {

        private ApplicationUserManager _userManager;
        private ApplicationDbContext _context;
        // GET: Questions
        //[Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            //var companionshipTypes = _context.CompanionshipType.ToList();
            //var userTypes = _context.UserType.ToList();
            //var addressTypes = _context.AddressType.ToList();
            //var documentTypes = _context.DocumentType.ToList();

            //var viewModel = new QuestionsViewModel
            //{
            //    CompanionshipTypes = companionshipTypes,
            //    UserTypes = userTypes,
            //    AddressTypes = addressTypes,
            //    DocumentTypes = documentTypes
            //};

            return View();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [HttpPost]
        public async Task<ActionResult> New(QuestionsViewModel model)
        {
            //ApplicationDbContext _context = new ApplicationDbContext();

            var indID = await UserManager.FindByEmailAsync(User.Identity.Name);
            try
            {

                _context = new ApplicationDbContext();
                //List<CompanionshipType> list = _context.CompanionshipType.ToList();
                //ViewBag.DepartmentList = new SelectList(list, "DepartmentId", "DepartmentName");

                // put things in lists that need to be in lists??

                //pull in this modelview from db so when questionnaire loads,
                //previous entries are laoded... (continue where they left off)

                // PUT ALL MODEL INPUTS HERE
                // assign all entries to their model.counterparts
                // add to _context
                // _context.savechanges

                // gets the current individualID from db.
                Individual individual = await _context.Individual.SingleOrDefaultAsync(m => m.IndividualID == indID.IndividualID);
                var latestID = individual.IndividualID;
                int relatedtortCase = individual.TortCaseID;

                individual.UserFirst = model.UserFirst;
                individual.UserLast = model.UserLast;
                individual.UserMiddle = model.UserMiddle;
                individual.UserMaiden = model.UserMaiden;
                individual.Gender = model.Gender;
                individual.Occupation = "INDIVIDUAL";
                if (model.DateOfBirth.HasValue)
                    individual.DateOfBirth = model.DateOfBirth.Value;
                individual.PlaceOfBirth = model.PlaceOfBirth;
                individual.Dependent = individual.Dependent;
                individual.EmployerName = model.vicEmployerName;
                individual.EmployerNumber = individual.EmployerNumber;
                individual.PhoneNumber = individual.PhoneNumber;
                individual.Email = indID.Email;
                individual.DateAdded = System.DateTime.Now;
                individual.GuardianshipDetails = "INDIVIDUAL";

                individual.IndividualRelationID = latestID;
                //get tortcase throught the view??
                individual.TortCaseID = relatedtortCase;
                individual.UserTypeID = individual.UserTypeID;
                individual.CompanionshipTypeID = model.CompanionshipTypeID;
                individual.IndividualRelatedTo = null;
                individual.EmailConfirmed = individual.EmailConfirmed;

                // updating the first user instead of adding a new one...
                var aspnetuserInDb = UserManager.FindByEmail(individual.Email); // this finds a user by the email in the model view. CORRECT
                UserManager.Update(aspnetuserInDb);

                //_context.Individual.Add(individual);
                _context.SaveChanges();

                Address addressResidential = new Address();
                addressResidential.IndividualID = latestID;
                addressResidential.AddressTypeID = 2;
                addressResidential.StreetNumber = model.StreetNumber;
                addressResidential.StreetName = model.StreetName;
                addressResidential.Suburb = model.Suburb;
                addressResidential.PostCode = model.PostCode;
                addressResidential.State = model.State;
                addressResidential.Country = model.Country;

                _context.Address.Add(addressResidential);
                _context.SaveChanges();

                //// spouse individual
                Individual spouseIndividual = new Individual();
                spouseIndividual.UserTypeID = 5;
                spouseIndividual.UserFirst = model.spouseUserFirst;
                spouseIndividual.UserLast = model.spouseUserLast;
                spouseIndividual.UserMiddle = model.spouseUserMiddle;
                spouseIndividual.UserMaiden = model.spouseUserMaiden;
                if (true)
                    spouseIndividual.DateOfBirth = System.DateTime.Now;
                spouseIndividual.PlaceOfBirth = "SPOUSE";
                spouseIndividual.Gender = "SPOUSE";
                spouseIndividual.DateAdded = System.DateTime.Now;
                spouseIndividual.GuardianshipDetails = "SPOUSE";
                spouseIndividual.IndividualRelationID = latestID;
                //get tortcase throught the view??
                spouseIndividual.TortCaseID = relatedtortCase;
                spouseIndividual.CompanionshipTypeID = model.CompanionshipTypeID;
                spouseIndividual.PhoneNumber = model.spousePhoneNumber;
                spouseIndividual.Email = model.spouseEmail;
                spouseIndividual.Occupation = model.spouseOccupation;

                _context.Individual.Add(spouseIndividual);
                _context.SaveChanges();
                int VLSID = spouseIndividual.IndividualID;

            //    PostMortemService spousedead = new PostMortemService();
            //    spousedead.IndividualID = VLSID;
            //    spousedead.cos
            ////date of death of spouse???
            //// spouse dead bool??

                //_context.PostMortemService.Add(spousedead);
                //_context.SaveChanges();

                Address VLSaddress = new Address();
                VLSaddress.AddressTypeID = 2;
                VLSaddress.IndividualID = VLSID;
                VLSaddress.StreetNumber = model.VLSStreetNumber;
                VLSaddress.StreetName = model.VLSStreetName;
                VLSaddress.Suburb = model.VLSSuburb;
                VLSaddress.State = model.VLSState;
                VLSaddress.Country = model.VLSCountry;

                _context.Address.Add(VLSaddress);
                _context.SaveChanges();

                DefactoCompanion defactoIndividual = new DefactoCompanion();
                defactoIndividual.IndividualID = VLSID;
                defactoIndividual.RelationshipContinued = model.RelationshipContinued;
                defactoIndividual.DateOfCommencementOfRelationship = model.DateOfCommencementOfRelationship;
                defactoIndividual.NumberOfChildren = model.NumberOfChildren;
                //wedding cert
                //spouse birth cert
                //companion birth cert
                //defactoIndividual.DateOfMarriage = model.DateOfMarriage;
                defactoIndividual.FacsimileNumber = model.spouseFacsimile;
                // where to put companion facsimile
                //defactoIndividual.FacsimileNumber = model.compFacsimile;

                _context.DefactoCompanion.Add(defactoIndividual);
                _context.SaveChanges();

                ////companion individual
                Individual compIndividual = new Individual();
                compIndividual.UserTypeID = 8;
                compIndividual.UserFirst = model.compUserFirst;
                compIndividual.UserLast = model.compUserLast;
                compIndividual.UserMiddle = model.compUserMiddle;
                compIndividual.UserMaiden = model.compUserMaiden;
                if (model.DateOfBirth.HasValue)
                    compIndividual.DateOfBirth = System.DateTime.Now;
                compIndividual.PlaceOfBirth = "COMPANION";
                compIndividual.Gender = "COMPANION";
                compIndividual.DateAdded = System.DateTime.Now;
                compIndividual.GuardianshipDetails = "COMPANION";
                compIndividual.IndividualRelationID = latestID;
                //get tortcase throught the view??
                compIndividual.TortCaseID = relatedtortCase;
                compIndividual.CompanionshipTypeID = 2;
                compIndividual.PhoneNumber = model.compPhoneNumber;
                compIndividual.Email = model.compEmail;
                compIndividual.Occupation = model.compOccupation;
                compIndividual.EmployerName = model.compEmployerName;

                _context.Individual.Add(compIndividual);
                _context.SaveChanges();
                int compID = compIndividual.IndividualID;

                ////companion address's
                Address compaddress = new Address();
                compaddress.AddressTypeID = 2;
                compaddress.IndividualID = compID;

CapstoneMVC/Views/Questions/CaseSelector.cshtml
@{
    ViewBag.Title = "CaseSelector";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Which Case Are You Submitting For?</h2>
<hr />

@*only show cases that they are tied to/allowed to complete*@

<div class="jumbotron">
    <table id="cases" class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Case</th>
            <th>Date Added</th>
            <th>Details</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@*need to pass the tortCaseId through to the questionviewmodel to create a new set of questions relating to THAT case*@

@section scripts
{
    <script>
        $(document).ready(function() {
            var casetable = $("#cases").DataTable({
                ajax: {
                    url: "/api/cases",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "caseName",
                        render: function(data, type, tortCase) {
                            return "<a href='/questions/new'>" + tortCase.caseName + "</a>";
                        }
                    },
                    {
                        data: "dateAdded"
                    },
                    {
                        data: "caseDescription",
                        render: function(data, type, tortCase) {
                            return "<a href='/cases/details/" + tortCase.tortCaseID +"'>" + "Details" + "</a>";
                        }
                    }
                ]
            });

            $("#cases").on("click",
            ".js-continue",
            function() {
                var button1 = $(this);
                bootbox.confirm("You will now be re-directed to continue your submission.",
                    function(result) {
                        if (result) {
                            $.ajax({
                                url: "/api/cases/" + button1.attr("data-tortCase-tortCaseID"),
                                success: function() {
                                    // take you to continue current submission from tortCaseId
                                }
                            });
                        }
                    });
                });

            $("#cases").on("click",
                ".js-discard",
                function() {
                    var button2 = $(this);
                    bootbox.confirm("Are you sure you want to delete this case?",
                        function(result) {
                            if (result) {
                                $.ajax({
                                    url: "/api/cases/" + button2.attr("data-tortCase-tortCaseID"),
                                    method: "DELETE",
                                    success: function() {
                                        casetable.row(button2.parents("tr")).remove().draw();
                                    }
                                });
                            }
                        });
                });
        });
    </script>
}

CapstoneMVC/Views/Questions/Index.cshtml
@using CapstoneMVC.Models

@{
    ViewBag.Title = "Submissions";
}
<h2>Active Submissions</h2>
<hr />

@*<p>Make list of cases associated with client/victim to choose from to fill out questionnaire for</p>*@
<div class="jumbotron">
    <table id="cases" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Case Name</th>
                <th>Date Added</th>
                <th>Case Details</th>
                <th>Current Submission</th>
            </tr>
        </thead>
        <tbody>
            @*
            <tr>
                will have to check the current user logged in and get all cases associated with them
                <td width="75%">You have no cases to continue with... Start a new one by clicking on your email in the top right!</td>
                <td>dd/mm/yyyy</td>
            </tr>*@
        </tbody>
    </table>
    @*@Html.ActionLink("Fill out the Questionnaire", "QuestionForm", "Questions")*@
</div>

@section scripts
{
<script>
    $(document).ready(function () {
        var casetable = $("#cases").DataTable({
            ajax: {
                url: "/api/cases",
                dataSrc: ""
            },
            columns: [
                {
                    data: "caseName",
                    //render: function(data, type, tortCase) {
                    //    return "<a href='/cases/edit/" + tortCase.tortCaseId + "'>" + tortCase.caseName + "</a>";
                    //}
                },
                {
                    data: "dateAdded"
                },
                {
                    data: "caseDescription",
                    render: function (data, type, tortCase) {
                        return "<a href='/cases/details/" + tortCase.tortCaseID + "'>" + "Details" + "</a>";
                    }
                },
                {
                    data: "tortCaseId",
                    render: function (data) {
                        return "<button class='btn-link js-continue' data-tortCase-tortCaseID=" + data + ">Continue</button>" + " / " +
                            "<button class='btn-link js-discard' data-tortCase-tortCaseID=" + data + ">Discard</button>";
                        //return "<a href='/questions/new" + tortCase.tortCaseId + "'>" + "Continue" + "</a>" + " / " +
                        //        "<a href='/questions/new" + tortCase.tortCaseId + "'>" + "Discard" + "</a>";
                    }
                }
            ]
        });

        $("#cases").on("click",
            ".js-continue",
            function () {
                var button1 = $(this);
                bootbox.confirm("You will now be re-directed to continue your submission.",
                    function (result) {
                        if (result) {
                            $.ajax({
                                url: "/api/cases/" + button1.attr("data-tortCase-tortCaseID"),
                                success: function () {
                                    // take you to continue current submission from tortCaseId
                                }
                            });
                        }
                    });
            });

        //dont want a client to be able to delete a case, only their current submission of data.....
        $("#cases").on("click",
            ".js-discard",
            function () {
                var button2 = $(this);
                bootbox.confirm("Are you sure you want to delete this case?",
                    function (result) {
                        if (result) {
                            $.ajax({
                                url: "/api/cases/" + button2.attr("data-tortCase-tortCaseID"),
                                method: "DELETE",
                                success: function () {
                                    // remove all data from submission and start a clean submission
                                }
                            });
                        }
                    });
            });
    });
</script>
}