CapstoneMVC/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CapstoneMVC.Models
{
    public class Document
    {
        [Key]
        public int DocumentID { get; set; }

        [Display(Name = "Uploaded File")]
        public string DocumentName { get; set; }

        public byte[] DocumentContent { get; set; }

        public string DocumentContentType { get; set; }

        public DocumentType DocumentType { get; set; }
        [ForeignKey("DocumentType")]
        public int DocumentTypeID { get; set; }

        public Individual Individual { get; set; }
        [ForeignKey("Individual")]
        public int IndividualID { get; set; }
    }
}

CapstoneMVC/Models/DocumentType.cs
using System.ComponentModel.DataAnnotations;

namespace CapstoneMVC.Models
{
    public class DocumentType
    {
        [Key]
        public int DocumentTypeID { get; set; }
        public string Name { get; set; }
    }
}

CapstoneMVC/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;
using CapstoneMVC.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity.Owin;

// trying to implement document uploads and downloads...


namespace CapstoneMVC.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {

        private ApplicationUserManager _userManager;
        private ApplicationDbContext _context;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Home
        public ActionResult Index()
        {
            return View(GetFiles());
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Index(HttpPostedFileBase postedFile)
        {
            var indID = await UserManager.FindByEmailAsync(User.Identity.Name);


            _context = new ApplicationDbContext();

            Individual individual = await _context.Individual.SingleOrDefaultAsync(m => m.IndividualID == indID.IndividualID);
            int latestID = individual.IndividualID;

            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "INSERT INTO FileModels VALUES (@Name, @ContentType, @Data, @IndividualID)";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    cmd.Parameters.AddWithValue("@Name", Path.GetFileName(postedFile.FileName));
                    cmd.Parameters.AddWithValue("@ContentType", postedFile.ContentType);
                    cmd.Parameters.AddWithValue("@Data", bytes);
                    cmd.Parameters.AddWithValue("@IndividualID", latestID);
                    con.Open();
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }

            return View(GetFiles());
        }

        [HttpPost]
        public FileResult DownloadFile(int? fileId)
        {
            byte[] bytes;
            string fileName, contentType;
           int Id_tag;
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "SELECT Name, Data, ContentType, IndividualID FROM FileModels WHERE Id=@Id";
                    cmd.Parameters.AddWithValue("@Id", fileId);
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        sdr.Read();
                        bytes = (byte[])sdr["Data"];
                        contentType = sdr["ContentType"].ToString();
                        fileName = sdr["Name"].ToString();
                        Id_tag = Convert.ToInt32(sdr["IndividualID"]);
                    }
                    con.Close();
                }
            }

            return File(bytes, contentType, fileName);
        }

        private static List<FileModel> GetFiles()
        {
            List<FileModel> files = new List<FileModel>();
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand("SELECT Id, Name, IndividualID FROM FileModels"))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            files.Add(new FileModel
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                Name = sdr["Name"].ToString(),
                                IndividualID = Convert.ToInt32(sdr["IndividualID"])
                            });
                        }
                    }
                    con.Close();
                }
            }
            return files;
        }
    }
}

CapstoneMVC/Views/Document/Index.cshtml
@using CapstoneMVC.Controllers
@using CapstoneMVC.Models
@model IEnumerable<CapstoneMVC.Models.FileModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Document Submissions</h2>
<hr />

@*No time to implement datatables here*@
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <div class="jumbotron">
        @*For some reason this isnt working*@
        @*
        @if (User.IsInRole(RoleName.TortClient))
        {
            @Html.Partial("_clientdocuments")
        }
        else
        {
            @Html.Partial("_blankhtml")
        }
        *@

        @using (Html.BeginForm("Index", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="postedFile" />
            <input type="submit" id="btnUpload" value="Upload" />
        }

        @using (Html.BeginForm("DownloadFile", "Document", FormMethod.Post))
        {
            <input type="hidden" id="hfFileId" name="FileId" />
            <input type="submit" id="btnDownload" value="Download" style="display:none" />
        }

        <br>
        <table class="table">
            <tr>
                <th width="10%">File ID</th>
                <th width="70%">File Name</th>
                <th width="10%">Individual ID</th>
                <th width="10%">Download</th>
            </tr>
            @if (Model.Count() > 0)
            {
                foreach (var file in Model)
                {
                    <tr>
                        <td>@file.Id</td>
                        <td>@file.Name</td>
                        <td>@file.IndividualID</td>
                        <td><a href="javascript:;" onclick="DownloadFile(@file.Id)">Download</a></td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">&nbsp;</td>
                </tr>
            }
        </table>

        @Html.ActionLink("Return", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-primary" })

    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        function DownloadFile(fileId) {
            $("#hfFileId").val(fileId);
            $("#btnDownload")[0].click();
        };
    </script>
</body>
</html>

CapstoneMVC/Views/Document/_clientdocuments.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
        @Html.BeginForm("Index", "Document", FormMethod.Post, new { enctype = "multipart/form-data" })
        {
            <input type="file" name="postedFile" />
            <input type="submit" id="btnUpload" value="Upload" />
        }

        @Html.BeginForm("DownloadFile", "Document", FormMethod.Post)
        {
            <input type="hidden" id="hfFileId" name="FileId" />
            <input type="submit" id="btnDownload" value="Download" style="display:none" />
        }
}